
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    networks:
      - frontend
      - backend

  php-fpm:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./www:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER:
      MYSQL_PASSWORD:
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "6001:80"
    networks:
      - backend

networks:
  frontend:
  backend:

